version: "3.8"

services:
  vertical_tables:
    build: .
    ports:
      - "1304:5000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    read_only: true
    cap_drop:
      - all
    privileged: true
    